### ISSUE TITLE
Case-Insensitvity auflösen

### ISSUE THREAD

**Issue by GameTagger507** [TGM-HIT/sew9-2324-worttrainer-Birgauan09#1]
Hallo, in deinem Projekt hast du deine Eingaben nicht case-sensitive gemacht, was nicht unbedingt der Sinn dieser Aufgabe ist. Diese Änderung wäre ein guter Schritt, den Kindern auch gleich Groß- und Kleinschreibung beizubringen.

**Comment by Birgauan09** [comment]
Hallo Emmanuel!
Danke für deinen guten Vorschlag. Das Problem über die Groß- und Kleinschreibung wurde behoben.
Mit freundlichen Grüßen,
Dawid Birgauan
